name: Release

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Validate"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: NPM Registry Auth
        run: |
          yarn logout
          echo "@matterbeam:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: lerna publish --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
