name: Size

on:
  pull_request:
    branches:
      - main

jobs:
  # danger:
  #   runs-on: ubuntu-latest
  #   name: Check for Danger errors
  #   env:
  #     DANGER_DISABLE_TRANSPILATION: true
  #     GITHUB_TOKEN: ${{secrets.DANGER_GITHUB_API_TOKEN}}
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Use Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 16.13.1

  #     - name: Run Danger Checks
  #       uses: danger/danger-js@10.7.1

  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
